services:

    app.menu_builder:
        class: AdminBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }

    admin.product:
        class: AdminBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Product }

    admin.tag:
        class: AdminBundle\Admin\TagAdmin
        arguments: [~, AppBundle\Entity\Tag, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Tag }